enhanced_user.sex.*:
  type: config_entity
  label: 'Sex config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
